apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kctrl.carvel.dev/repository-version: 1.0.3
  creationTimestamp: "2024-03-09T18:18:27Z"
  name: watchdog-repo.local.com
spec:
  fetch:
    imgpkgBundle:
      image: ghcr.io/mitul01/watchdog-application@sha256:971375dd3ea24b3eca1427803496f409994468ae5c80054e668c17bb6627d808
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
