apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: watchdog-bots.local.com.1.0.2
spec:
  refName: watchdog-bots.local.com
  releasedAt: "2024-05-11T22:08:05Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/mitul01/watchdog-bots.local.com@sha256:52d39e9b663f8b738958bc7d4c65bf799899c217180e5d4be38450b877eeb7b5
      template:
      - ytt:
          paths:
          - k8s
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        label:
          additionalProperties: false
          properties:
            component:
              default: python-bots
              type: string
            managedBy:
              default: kapp-controller
              type: string
            partOf:
              default: watchdog-bots
              type: string
            version:
              default: 1.0.0
              type: string
          type: object
        namespace:
          default: watchdog
          type: string
        telegram:
          additionalProperties: false
          properties:
            env:
              additionalProperties: false
              properties:
                botToken:
                  default: ""
                  type: string
                graphqlUrl:
                  default: http://66.175.221.177:30000/graphql
                  type: string
              type: object
            image:
              default: watchdog-telegram-bot
              type: string
            name:
              default: watchdog-telegram-bot
              type: string
            replicas:
              default: 1
              type: integer
            secretName:
              default: telegram-service-secret
              type: string
          type: object
      type: object
  version: 1.0.2
